# These files will only get full coverage from running the functional
# tests, but those aren't run from CI
ignore:
  - "bugzilla/_backendrest.py"
  - "bugzilla/_backendxmlrpc.py"
  - "bugzilla/_session.py"
